spring:
  application:
    name: bin-checker-service
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
