spring:
  application:
    name: bin-checker-service
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "${MANAGEMENT_ENDPOINTS_EXPOSURE:*}"
  endpoint:
    health:
      show-details: "${MANAGEMENT_HEALTH_SHOW_DETAILS:always}"
      probes:
        enabled: true
