apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: tokenization-service
  namespace: tokenization-service
spec:
  selector:
    matchLabels:
      app: tokenization-service
  jwtRules:
    - issuer: "http://keycloak.k8s.orb.local/realms/dev"
      jwksUri: "http://keycloak.keycloak.svc.cluster.local/realms/dev/protocol/openid-connect/certs"
      forwardOriginalToken: true
