apiVersion: v1
kind: Service
metadata:
  name: opa-svc
  namespace: opa
spec:
  type: ClusterIP
  selector:
    app: opa
  ports:
    - name: grpc
      port: 9191
      targetPort: 9191
      protocol: TCP
    - name: http
      port: 8181
      targetPort: 8181
      protocol: TCP
