spring:
  application:
    name: tokenization-service
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "${MANAGEMENT_ENDPOINTS_EXPOSURE:*}"
  endpoint:
    health:
      show-details: "${MANAGEMENT_HEALTH_SHOW_DETAILS:always}"
      probes:
        enabled: true

clients:
  bin-checker:
    url: "${CLIENTS_BIN_CHECKER_URL:http://bin-checker-service:8080}"
    connect-timeout: "${CLIENTS_BIN_CHECKER_CONNECT_TIMEOUT:2000}"
    read-timeout: "${CLIENTS_BIN_CHECKER_READ_TIMEOUT:5000}"
