@dns = k8s.orb.local

###################################################
### Auth - well-known
###################################################
GET http://keycloak.{{dns}}/realms/master/.well-known/openid-configuration

###################################################
### Auth - access_token
###################################################
# @name auth
POST http://keycloak.{{dns}}/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=rest-client
&client_secret=2fvZj1YpJ6QQnjlr3Hx09lgf1xHrkmae
&scope=openid

### access_token
@access_token = {{auth.response.body.access_token}}
###################################################
### Auth - well-known
###################################################

###################################################
### BinChecker - health
###################################################
GET http://bin-checker-service.{{dns}}/actuator/health
Accept: application/json

###################################################
### BinChecker
###################################################
GET http://bin-checker-service.{{dns}}/v1/bin/411111
Accept: application/json
Authorization: Bearer {{access_token}}
