@dns = k8s.orb.local
@realm = dev

###################################################
### Auth - well-known
###################################################
# @name well_known
GET http://keycloak.{{dns}}/realms/{{realm}}/.well-known/openid-configuration

###################################################
### Auth - access_token
###################################################
# @name auth
POST {{well_known.response.body.token_endpoint}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=rest-client
&client_secret=ZoxeWS2LdJEtilfoTxLvJtOnhsnGIQQT
&scope=openid

### access_token
@access_token = {{auth.response.body.access_token}}

###################################################
### BinChecker - health
###################################################
GET http://bin-checker-service.{{dns}}/actuator/health
Accept: application/json

###################################################
### BinChecker
###################################################
GET http://bin-checker-service.{{dns}}/v1/bin/411111
Accept: application/json
Authorization: Bearer {{access_token}}
